### ISSUE TITLE
Compiling issues

### ISSUE THREAD

**Issue by Shisir99** [stanford-oval/thingtalk#406]
I want to run a thingtalk program , how can I do it using this compiler?

**Comment by gcampax** [comment]
The compiler is quite low-level. It will produce a JavaScript function that runs in a ThingTalk runtime. If you're a user, the ThingTalk runtime is provided by genie-toolkit.

If you're a dev, you need to build a runtime that implements this class https://github.com/stanford-oval/thingtalk/blob/master/lib/runtime/exec_environment.ts#L64
Then the compiled program produced by the compiler ( https://github.com/stanford-oval/thingtalk/blob/master/lib/runtime/exec_environment.ts#L47 ) will be a set of JS functions that you can pass the runtime object to.

Closing this, because it's not really an issue. In the future, please use our community forum (community.almond.stanford.edu) for support questions!
